services:
  rk-core-builder-3326-32:
    build:
      context: .
      args:
        - ARCH=armhf
        - CHIP=rk3326
        - QEMU=arm
    image: rk-core-builder-3326-32
    container_name: rk-core-builder-3326-32
    privileged: true
    volumes:
      - .:/mnt/host

  rk-core-builder-3326-64:
    build:
      context: .
      args:
      - ARCH=arm64
      - CHIP=rk3326
      - QEMU=aarch64
    image: rk-core-builder-3326-64
    container_name: rk-core-builder-3326-64
    privileged: true
    volumes:
      - .:/mnt/host

  rk-core-builder-3566-32:
    build:
      context: .
      args:
        - ARCH=armhf
        - CHIP=rk3566
        - QEMU=arm
    image: rk-core-builder-3566-32
    container_name: rk-core-builder-3566-32
    privileged: true
    volumes:
      - .:/mnt/host

  rk-core-builder-3566-64:
    build:
      context: .
      args:
        - ARCH=arm64
        - CHIP=rk3566
        - QEMU=aarch64
    image: rk-core-builder-3566-64
    container_name: rk-core-builder-3566-64
    privileged: true
    volumes:
      - .:/mnt/host
